CREATE TABLE [dbo].[Radnja](
	[PIB] [int] IDENTITY(1,1) NOT NULL,
	[Naziv] [nvarchar](50) NULL,
	[Adresa] [nvarchar](50) NULL,
	[BrTel] [int] NULL,
	[ZiroRacun] [int] NULL,
 CONSTRAINT [PK__Radnja__C57755267F60ED59] PRIMARY KEY CLUSTERED 
(
	[PIB] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hrana](
	[HranaID] [int] IDENTITY(1,1) NOT NULL,
	[Naziv] [nvarchar](50) NULL,
	[Gramaza] [nvarchar](50) NULL,
	[Cena] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[HranaID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Radnik](
	[RadnikID] [int] IDENTITY(1,1) NOT NULL,
	[Ime] [nvarchar](50) NULL,
	[Prezime] [nvarchar](50) NULL,
	[BrTel] [int] NULL,
	[Adresa] [nvarchar](50) NULL,
	[PIB] [int] NOT NULL,
 CONSTRAINT [PK__Radnik__ABC4C75A03317E3D] PRIMARY KEY CLUSTERED 
(
	[RadnikID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Prodaja](
	[ProdajaID] [int] IDENTITY(1,1) NOT NULL,
	[Datum] [date] NULL,
	[HranaID] [int] NULL,
	[PiceID] [int] NULL
PRIMARY KEY CLUSTERED 
(
	[ProdajaID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Pice](
	[PiceID] [int] IDENTITY(1,1) NOT NULL,
	[NazivPice] [nvarchar](50) NULL,
	[ML] [int] NULL,
	[Cena] [int] NULL,
	[RadnikID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[PiceID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[Radnik]  WITH CHECK ADD  CONSTRAINT [FK_Radnik_Radnja] FOREIGN KEY([PIB])
REFERENCES [dbo].[Radnja] ([PIB])
GO
ALTER TABLE [dbo].[Radnik] CHECK CONSTRAINT [FK_Radnik_Radnja]
GO

ALTER TABLE [dbo].[Prodaja]  WITH CHECK ADD  CONSTRAINT [FK_Prodaja_Hrana] FOREIGN KEY([HranaID])
REFERENCES [dbo].[Hrana] ([HranaID])
GO
ALTER TABLE [dbo].[Prodaja] CHECK CONSTRAINT [FK_Prodaja_Hrana]
GO

ALTER TABLE [dbo].[Prodaja]  WITH CHECK ADD  CONSTRAINT [FK_Prodaja_Pice] FOREIGN KEY([PiceID])
REFERENCES [dbo].[Pice] ([PiceID])
GO
ALTER TABLE [dbo].[Prodaja] CHECK CONSTRAINT [FK_Prodaja_Pice]
GO